services:
  istio-gateway:
    labels:
      "gateway": "external"
    global_permissions:
    - "get,watch,list,update extensions/thirdpartyresources"
    - "get,watch,list,update */virtualservices"
    - "get,watch,list,update */destinationrules"
    - "get,watch,list,update */gateways"
    update_order: stop-first
    sidekicks:
      istio-proxy:
        ports: ${PORTS}
        image: "istio/proxyv2:1.0.2"
        command:
        - proxy
        - router
        - -v
        - "2"
        - --discoveryRefreshDelay
        - '1s' #discoveryRefreshDelay
        - --drainDuration
        - '45s' #drainDuration
        - --parentShutdownDuration
        - '1m0s' #parentShutdownDuration
        - --connectTimeout
        - '10s' #connectTimeout
        - --serviceCluster
        - istio-proxy
        - --zipkinAddress
        - ""
        - --statsdUdpAddress
        - ""
        - --proxyAdminPort
        - "15000"
        - --controlPlaneAuthPolicy
        - NONE
        - --discoveryAddress
        - istio-pilot:15007
        env:
        - POD_NAME=$(self/name)
        - POD_NAMESPACE=$(self/namespace)
        - INSTANCE_IP=$(self/ip)
        - ISTIO_META_POD_NAME=$(self/name)
        secrets: identity:/etc/certs
