configs:
  kiali-config:
    content: |-
      server:
        port: 20001
      external_services:
        grafana:
          url: ${GRAFANA_URL}
services:
  kiali:
    global_permissions:
    - "get,list,watch networking.istio.io/virtualservices"
    - "get,list,watch networking.istio.io/destinationrules"
    - "get,list,watch networking.istio.io/serviceentries"
    - "get,list,watch networking.istio.io/gateways"
    - "get,list,watch config.istio.io/*"
    - "get,list,watch /*"
    - "get,list,watch batch/*"
    - "get,list,watch apps/*"
    - "get,list,watch autoscaling/*"
    image: docker.io/kiali/kiali:v0.10
    environment:
    - ACTIVE_NAMESPACE=${NAMESPACE}
    - SERVER_CREDENTIALS_USERNAME=${USERNAME}
    - SERVER_CREDENTIALS_PASSWORD=${PASSWORD}
    - PROMETHEUS_SERVICE_URL=${PROMETHEUS_URL}
    command:
    - -config
    - /kiali-configuration/config.yaml
    - -v
    - '4'
    configs:
    - kiali-config:/kiali-configuration/config.yaml
    expose:
    - 20001/http

externalservices:
  prometheus:
    service: prometheus/prometheus
  grafana:
    service: grafana/grafana

questions:
  - variable: USERNAME
    description: "username to login dashboard"
  - variable: PASSWORD
    description: "password to login dashboard"
